basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#template URLs
app_name='basicapp'
urlpatterns = [
  url(r'^register/$',views.register,name='register'),
  url(r'^user_login/$',views.user_login,name='user_login'),


]

level5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicapp import views
urlpatterns = [
  url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
      url(r'^basicapp/',include('basicapp.urls')),
      url(r'^logout/$',views.user_logout,name='logout'),
      url(r'^special/',views.special,name='special')
    
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# call user model
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #additional information
    profile_pic=models.ImageField(upload_to='profilepics',blank=True)
    # if user doesnot want to upload photo


    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo
# model name and form name not be same
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('profile_pic',)

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse

from django.contrib.auth.decorators import login_required






def index(request):
    return render(request,'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered=False

    if request.method=="POST":
        userform=UserForm(data=request.POST)
        profileform=UserProfileInfoForm(data=request.POST)

        if userform.is_valid() and profileform .is_valid():
            user=userform.save()
            user.set_password(user.password)
            # password to hash table
            user.save()
            profile=profileform.save(commit=False)
            profile.user=user
            # provide one to one relationship so no collision


            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(userform.errors,profileform.errors)


    else:
        userform=UserForm()
        profileform=UserProfileInfoForm()



    return render(request,'basicapp/registration.html',{'userform':userform,'profileform':profileform,'registered':registered})



def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basicapp/login.html', {})

templates/basicapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>HOME</title>
  </head>
  <body>




    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">HOME</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">


          <li class="nav-item">
            <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{%url 'basicapp:register'%}">Register</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'basicapp:user_login' %}">Login</a>
          </li>
          {% endif %}

        </ul>
        </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>

{%extends "basicapp/base.html"%}
{%block body_block%}

<div class="jumbotron">
  <h1>Welcome to the registration project</h1>


</div>
{%endblock%}

templates/basicapp/login.html
{%extends 'basicapp/base.html'%}
{%block body_block%}

<div class="jumbotron">
  <h1>Please Login </h1>
  <form  action="{% url 'basicapp:user_login' %}" method="post">

    {%csrf_token%}
    <label for="username">Username :</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password :</label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="Login">

  </form>

</div>
{%endblock%}

templates/basicapp/registration.html
<!DOCTYPE html>
{%extends 'basicapp/base.html'%}
{% load staticfiles %}
{%block body_block%}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering !</h1>
    {%else%}
    <h1>Register Here !</h1>
    <h3>Fill out the form :</h3>
      <form  method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{userform.as_p}}
        {{profileform.as_p}}
        <input type="submit" name="" value="Register">

      </form>
  {%endif%}

</div>
{%endblock%}